name: Jason Butz
pygments: true
timezone: America/Indianapolis
permalink: /:categories/:title.html
tagline: A developer with a love for the web
paginate: 5
paginate_path: "blog/page:num"
url: http://www.jasonbutz.info